### ISSUE TITLE
Double Metaphone - panicked at 'attempt to subtract with overflow'

### ISSUE THREAD

**Issue by Marc-Eluard** [Dalvany/rphonetic#47]
Hello,

I use this library on user entries. These entries concern first names, and some of them crash the library when I use the Double Metaphone algorithm with the alternative version.

For example, "LLANA" and "CCILE" crash the library. This isn't the case for all strings that start with "CC" or "LL", "LLOYD" works.
The error message:  `thread 'main' panicked at 'attempt to subtract with overflow', rphonetic-2.1.4\src\double_metaphone.rs:711:38`

Here's the code I use:
```
use rphonetic::DoubleMetaphone;
fn main() {
   let dmetaphone: DoubleMetaphone = DoubleMetaphone::default();
   let result: String = dmetaphone.encode_alternate("LLANA");
   println!("{result}");
}
```
Behavior is the same with version 2.1.15

**Comment by Dalvany** [comment]
@Marc-Eluard
Hello, it be fixed in 2.2.0, which is released.
Let me know if it's ok or not.

**Comment by Marc-Eluard** [comment]
Hello,
What responsiveness, thank you.
I tested it on all the strings I had and it didn't crash, it's perfect.
Thank you

**Comment by Dalvany** [comment]
Hum, I don't know why there's a difference. 
Did you try a 'cargo clean' and/or 'cargo update' ?

**Comment by Marc-Eluard** [comment]
Hello,
I've updated the libraries and Rust (1.77.2) and I still have the same behavior.
In Release, everything is perfect and in Dev, the library crashes.
I don't know enough about Rust to be able to analyze this phenomenon. I don't know if this has an impact, but I use Cargo.
In any case, I have a version that works and that's the best.
Thanks

**Comment by Dalvany** [comment]
Ok, I close the issue then. Don't hesitate to re-open it if needed !

**Comment by Marc-Eluard** [comment]
Yes, I also tried "cargo clean" and "cargo update" and same results.

Thanks
